First Commit of plugin with Menu Items
joplin/plugin-paste-special pull request #1
Opened 2021-06-18 13:54 UTC by coderrsid

Here, i have created menu items under `Edit` toolbar menu named `Paste Special` and `Import Special` as for the UI

2021-06-20 08:36 UTC, laurent22 requested changes

2021-06-20 08:36 UTC, laurent22 commented on src/pasteCsvAsTable.ts
> + export function pasteCsvAsTable(csvContent: string, delimiter: string = "\t", hasHeader: boolean = false): string {
There's two issues with this file:

1. It was copied from [here](https://github.com/donatj/CsvToMarkdownTable/blob/master/src/CsvToMarkdown.ts) but you didn't provide any attribution, or told us about it. We need to know where the code comes from so that we can verity that the license is valid (it is), and that we know what you've created and what you've borrowed.

2. It's not good practice to copy and paste large files like this one, because it means you won't benefit from any upstream improvements, unless you manually edit it. Any manual steps added to a project is more maintenance burden and in practice it's just not done. So if you want to use this library please import it as an npm package. If you don't know what I mean by that, or if you don't know how to import an npm package, please let me know.

2021-06-20 08:36 UTC, laurent22 commented on src/index.ts
> +});
There are lots of files in this pull requests, but most are just from the plugin template. Am I correct to think this is the only file that's from you? Just want to make sure I'm not missing any.

2021-06-20 10:42 UTC, coderrsid commented on src/pasteCsvAsTable.ts
> + export function pasteCsvAsTable(csvContent: string, delimiter: string = "\t", hasHeader: boolean = false): string {
Sure, i talked to the developer personally though. But that's fine, you're correct increases the burden so i'll use that as a package instead of code. 
Yeah and about the PapaParse package, i had an idea to parse CSV into a JSON and then convert that JSON with a package to MD table when copied or imported. But when i researched for a while these multiple steps can lead to many error and it increase space and time complexity too and doesn't undergo an efficient algorithm. So, instead i tried finding a way to convert CSV to MD table directly and that's where i found this code. So, i tried using that directly here because i wanted a review from all of us on this code too that shall we use another piece of code or package or this'd work fine.

2021-06-20 10:43 UTC, coderrsid commented on src/index.ts
> +});
Yes.

2021-06-20 11:38 UTC, laurent22 commented on src/pasteCsvAsTable.ts
> + export function pasteCsvAsTable(csvContent: string, delimiter: string = "\t", hasHeader: boolean = false): string {
The first project has 200 stars, the PapaParse has 10,000 so I think that should weight in your decision. Parsing CSV is [way harder than it seems](http://thomasburette.com/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/) and with 10k stars we can assume they've already dealt many edge cases.

Converting a JSON structure to Markdown is trivial so that shouldn't be an issue for you. And then you'll start with a much stronger library.

2021-06-20 11:43 UTC, laurent22 commented on src/index.ts
> +});
I must say, till now it's not entirely clear what you've done for the two weeks since coding started. I hope that for the coming weeks, you'll let us know your progress and if you reach any road block, please let us know as soon as possible.

We expect students not to know everything and to be stuck now and then. You just need to tell us.

2021-06-20 18:12 UTC, coderrsid commented on src/index.ts
> +});
Absolutely, laurent. I'll be in touch frequently.

2021-06-20 18:24 UTC, coderrsid commented on src/pasteCsvAsTable.ts
> + export function pasteCsvAsTable(csvContent: string, delimiter: string = "\t", hasHeader: boolean = false): string {
Sure. I understand. I'll consider using PapaParse as planned then.

2021-06-26 16:04 UTC, coderrsid commented
Are changes needed in this pull request for now?

2021-06-26 16:39 UTC, laurent22 commented
You wrote:

> Sure. I understand. I'll consider using PapaParse as planned then.

So do you plan to do this?

2021-06-29 00:30 UTC, coderrsid commented
> You wrote:
> 
> > Sure. I understand. I'll consider using PapaParse as planned then.
> 
> So do you plan to do this?

Yes, i'm using it in dev-test branch. Should i make a pull request from that branch and delete this one?

2021-06-29 07:01 UTC, laurent22 commented
Yes let's close this then.

2021-06-29 07:01 UTC, closed without merging